### ISSUE TITLE
.font no longer accepts UIFont, but Font doesn't work

### ISSUE THREAD

**Issue by dgable64** [MojtabaHs/iPhoneNumberField#10]
When using the following as shown in the examples:

                .font(UIFont(size: 24, weight: .light, design: .monospaced))

SwiftUI issues a compile-time error:

Cannot convert value of type 'UIFont?' to expected argument type 'Font?'

When I changed it to use Font as follows:

                     .font(.system( size: 24 ))

The change does not take effect, it just shows the standard default font and size.

I'd like to use this in a new project and will be buying the commercial license if I can get this working.

Thanks!

**Comment by dgable64** [comment]
Hmmm, I just noticed that using the Font works fine in the simulator but does not work on the device (at least iPhone 12 Pro Max).  Might be an Apple bug.

**Comment by MojtabaHs** [comment]
Yes maybe it is another Apple's bug! 🍎🐞

**Comment by edimoldovan** [comment]
I have this same issue on physical device (XR). Can't figure out what the issue is.

**Comment by edimoldovan** [comment]
`.frame` and `.padding` cause the compiler issue.
