### ISSUE TITLE
Textfield Reverts to Default When Selecting a Different Country

### ISSUE THREAD

**Issue by hamza-butt** [MojtabaHs/iPhoneNumberField#105]
When a user selects a country from the dropdown menu and begins typing the phone number associated with that country, the input field behaves unexpectedly. Specifically, after entering the first two digits of the phone number, the textfield reverts to the default state instead of continuing to accept the input in the selected country's format.

**Comment by ferrlan** [comment]
I am having the same issue with the most recent.

**Comment by sachithamh** [comment]
same issue

**Comment by sachithamh** [comment]
fix PR: https://github.com/MojtabaHs/iPhoneNumberField/pull/107

**Comment by djk8** [comment]
@hamza-butt @ferrlan did you guys ever get this fixed? i am experiencing this as well
