### ISSUE TITLE
Get the country code from iPhoneNumberTextField

### ISSUE THREAD

**Issue by elai950** [MojtabaHs/iPhoneNumberField#12]
I'm trying to get the full number including the country code of the typed number.
How do I receive it from iPhoneNumberTextField?

**Comment by Trystanr** [comment]
I'm having the same issue, the country code is not being displayed but the flag is visible.

**Comment by tadeha** [comment]
> I'm having the same issue, the country code is not being displayed but the flag is visible.

If you want to make the country code visible, you should add `.prefixHidden(false)` modifier.

**Comment by tadeha** [comment]
> I'm trying to get the full number including the country code of the typed number.
> How do I receive it from iPhoneNumberTextField?

You can access a phone number object using:
```
.onNumberChange { phoneNumber in
    print(phoneNumber)
}
```
It doesn't get called now, but after the next fix, I think it will be the solution.

**Comment by derkaramma** [comment]
Yes, I am having this same problem, you can choose which country but the code is not being collected. How do I capture the country code when a user selects their flag, if no flag is selected then use the users local country code.

**Comment by MojtabaHs** [comment]
it is accessible with `.onNumberChange` modifier.

```
.onNumberChange { phoneNumber in
    print("country code:", phoneNumber?.countryCode)
    print("number:", phoneNumber?.numberString)
}
```
Note that is will return `nil` if the number is not a valid number and that is why the `phoneNumber` object is optional!  You can also access to the yet not valid `text` with the `text` variable! If you need a live change  observer you can either use `text` variable or the `onEdit` modifier.

**Comment by MojtabaHs** [comment]
> I'm having the same issue, the country code is not being displayed but the flag is visible.

Showing the code is different from getting it. Please open another issue so we can take care of that.

**Comment by PhanithNoch** [comment]
Hello everyone, do you know to set default country code? because by default it's selected United States

**Comment by tadeha** [comment]
> Hello everyone, do you know to set default country code? because by default it's selected United States

I guess your current region is the US so it's showing it as default. You can change the default region using this modifier:

`.defaultRegion(_:)`

**Comment by iMtRo** [comment]
> > Hammaga salom, siz standart davlat kodini o'rnatishni bilasizmi? chunki sukut bo'yicha Amerika Qo'shma Shtatlari tanlangan
> 
> O'ylaymanki, sizning hozirgi hududingiz AQSh, shuning uchun u uni sukut bo'yicha ko'rsatmoqda. Ushbu modifikator yordamida standart mintaqani o'zgartirishingiz mumkin:
> 
> `.defaultRegion(_:)`


> `.defaultRegion(_:)`
>
>I couldn't find what to write in String to use this

**Comment by praveen0704-code** [comment]
can i show default contry code only
