### ISSUE TITLE
onEditingChange and onPhoneNumberChange handlers not initialized

### ISSUE THREAD

**Issue by Kitos-dev** [MojtabaHs/iPhoneNumberField#13]
.onEdit and .onNumberChange view modifiers are not being called because handlers are not initialized.
I see that this is fixed in https://github.com/MojtabaHs/iPhoneNumberField/commit/45c9eb3159b43bb3de02aa11639253ba7b59a5ab#diff-fbdc988991647c8b7c843fe2395ec48573e0edb60b2a26376dc12ed19b02b269 and already merged in master.
Could you just public a new release to make this available? Otherwise this cool framework is not so usable as usually phone number validation is needed somehow.

**Comment by richard-ash** [comment]
+1 it'd be great to get a release out with this. Thanks in advance!

**Comment by MojtabaHs** [comment]
[v0.5.5](https://github.com/MojtabaHs/iPhoneNumberField/releases/tag/0.5.5) is now available.
