### ISSUE TITLE
"Modifying state during view update, this will cause undefined behavior" when tapping to edit

### ISSUE THREAD

**Issue by byfu34** [MojtabaHs/iPhoneNumberField#15]
My iPhoneNumberField is crashing my app when it is tapped because it repeatedly throws a "Modifying state during view update, this will cause undefined behavior" error. The error highlights lines 234 and 239 of iPhoneNumberField.swift, which set isFirstResponder.wrappedValue in the textFieldDidBeginEditing and textFieldDidEndEditing functions.

**Comment by MojtabaHs** [comment]
It is an unknown warning flag that SwiftUI trows. Did you face any issues?

**Comment by beskostyi-ad** [comment]
Faced with same issue: "Modifying state during view update, this will cause undefined behavior."

```
iPhoneNumberField(nil, text: $firebaseAuth.phone, isEditing: $isEditing, formatted: false)
            .flagHidden(false)
            .prefixHidden(false)
            .flagSelectable(true)
            .autofillPrefix(true)
```

<img width="1190" alt="Screenshot 2021-03-05 at 14 43 28" src="https://user-images.githubusercontent.com/73350699/110117163-28b45880-7dc1-11eb-9217-6b6044923fa8.png">

**Comment by MojtabaHs** [comment]
Yes, it is an `undefined behavior`. I will fix it when it became `defined 😉
