### ISSUE TITLE
Does not accept leading zeros

### ISSUE THREAD

**Issue by Dreamystify** [MojtabaHs/iPhoneNumberField#16]
In Australia, we have state area codes beginning with zero

eg
(02) 9456 1234
(03) 9456 1234
(04) 9456 1234

Mobiles are 0404 123 456 for example

and this library isn't accepting the leading zeros, what am I doing wrong?

**Comment by tadeha** [comment]
> In Australia, we have state area codes beginning with zero
> 
> eg
> (02) 9456 1234
> (03) 9456 1234
> (04) 9456 1234
> 
> Mobiles are 0404 123 456 for example
> 
> and this library isn't accepting the leading zeros, what am I doing wrong?

Can you please put your `iPhoneNumberField` code with its modifiers?

**Comment by brandtdaniels** [comment]
I am seeing the same thing. I'm working on a US based app adding support for Australian customers.

**Comment by Dreamystify** [comment]
Ive got it somewhat working for (02) 4567 3762 where the following code:

```
@State private var phone = ""
@State private var isEditingPhone = false

iPhoneNumberField("Phone", text: self.$phone, isEditing: $isEditingPhone)
    .defaultRegion("AU")
    .prefixHidden(false)
    .flagHidden(true)
    .flagSelectable(false)
    .maximumDigits(10)
    .clearButtonMode(.whileEditing)
    .onClear { _ in isEditingMobile.toggle() }
     .keyboardType(.phonePad)
    .onChange(of: self.phone, perform: { value in
        do {
            let phoneNumber = try phoneNumberKit.parse(value)
            self.phone = phoneNumberKit.format(phoneNumber, toType: .national)
        } catch {}
    })
```
will format the number XX XXXX XXXX up till the last character is added and the 
on change validates to update it to (XX) XXXX XXXX

AU Mobiles 0404 123 456 work fine with

```
@State private var mobile = ""
@State private var isEditingMobile = false

iPhoneNumberField("Mobile", text: self.$mobile, isEditing: $isEditingMobile)
    .defaultRegion("AU")
    .prefixHidden(false)
    .flagHidden(true)
    .flagSelectable(false)
    .maximumDigits(10)
    .clearButtonMode(.whileEditing)
    .onClear { _ in isEditingMobile.toggle() }
    .keyboardType(.phonePad)
```

**Comment by MojtabaHs** [comment]
Good to hear that it is working now for your. You can use `.prefixHidden(false)` so  the place holder shows the country code and the textField accepts both country code and leading zero (as the country code). Also you can use `.autofillPrefix(true)` so user will get free prefill country code when selects the textfield.

**Comment by jasontcs** [comment]
> Ive got it somewhat working for (02) 4567 3762 where the following code:
> 
> ```
> @State private var phone = ""
> @State private var isEditingPhone = false
> 
> iPhoneNumberField("Phone", text: self.$phone, isEditing: $isEditingPhone)
>     .defaultRegion("AU")
>     .prefixHidden(false)
>     .flagHidden(true)
>     .flagSelectable(false)
>     .maximumDigits(10)
>     .clearButtonMode(.whileEditing)
>     .onClear { _ in isEditingMobile.toggle() }
>      .keyboardType(.phonePad)
>     .onChange(of: self.phone, perform: { value in
>         do {
>             let phoneNumber = try phoneNumberKit.parse(value)
>             self.phone = phoneNumberKit.format(phoneNumber, toType: .national)
>         } catch {}
>     })
> ```
> 
> will format the number XX XXXX XXXX up till the last character is added and the on change validates to update it to (XX) XXXX XXXX
> 
> AU Mobiles 0404 123 456 work fine with
> 
> ```
> @State private var mobile = ""
> @State private var isEditingMobile = false
> 
> iPhoneNumberField("Mobile", text: self.$mobile, isEditing: $isEditingMobile)
>     .defaultRegion("AU")
>     .prefixHidden(false)
>     .flagHidden(true)
>     .flagSelectable(false)
>     .maximumDigits(10)
>     .clearButtonMode(.whileEditing)
>     .onClear { _ in isEditingMobile.toggle() }
>     .keyboardType(.phonePad)
> ```

Seems `. maximumDigits(10)` not working as expected if the text has 0 as the prefix
