### ISSUE TITLE
Shouldn't country codes stay fixed when it's visible? (instead of just being placeholder)

### ISSUE THREAD

**Issue by tadeha** [MojtabaHs/iPhoneNumberField#17]
Currently, my `iPhoneNumberField` has these modifiers:
```
.flagHidden(false)
.flagSelectable(true)
.prefixHidden(false)
```
And works like this:
![Feb-01-2021 12-06-49](https://user-images.githubusercontent.com/22890731/106433932-1b384580-6486-11eb-82c3-1bd07e7f5e17.gif)

Shouldn't the country code be fixed (like the 3rd try I did in the gif), and the remaining job for the user is to enter his/her phone number only? (without the country code)

**Comment by derkaramma** [comment]
I can't even get the country code to populate. There is an issue thread going about it might be a similar problem to this one.

**Comment by MojtabaHs** [comment]
you can use the last argument of the initializer for now:

```
iPhoneNumberField(
    nil,
    text: $text,
    isEditing: $isFirstResponder) {
        $0.withExamplePlaceholder = true
}
````

**Comment by MojtabaHs** [comment]
From v0.5.6 you can use:
```
    .prefixHidden(false)
    .autofillPrefix(true)
```
