### ISSUE TITLE
Possible to override default region?

### ISSUE THREAD

**Issue by brandtdaniels** [MojtabaHs/iPhoneNumberField#19]
Is it possible to override the default region seen in the example on PhoneNumberKit?

```
class MyGBTextField: PhoneNumberTextField {
    override var defaultRegion: String {
        get {
            return "GB"
        }
        set {} // exists for backward compatibility
    }
}
```

**Comment by brandtdaniels** [comment]
Nevermind, I found it in the code, it just wasn't documented in the readme.

**Comment by MojtabaHs** [comment]
You can use  `.defaultRegion("GB")` modifier. And yes we should reconsider the readme file as soon as possible since there are many cool new features since it was written.
