### ISSUE TITLE
Title not appearing on versions after 0.5.4

### ISSUE THREAD

**Issue by brandtdaniels** [MojtabaHs/iPhoneNumberField#22]
I ran into an odd issue today where the title is not appearing on versions after 0.5.4. My local machine has cached 0.5.4 and I am able to see the title, but when Bitrise builds (clean everything) for me it is pulling down 0.6.1 and the title is missing.

**Comment by brandtdaniels** [comment]
I finally got time to narrow this down a bit. Updating one version at a time starting at 0.5.4, the placeholder title didn't go missing until 0.6.0.

**Comment by mehmetsen80** [comment]
The Placeholder doesn't work

**Comment by Nauxie** [comment]
The placeholder is missing for me too. Anybody able to find a fix?

**Comment by dns-mcdaid** [comment]
I think I've got a fix in #25. Credit to @brandtdaniels for finding the breaking line. Not sure if there's a more elegant solution, but hopefully this means we're closer to a working patch 😅

**Comment by MojtabaHs** [comment]
Fixed v0.6.2
