### ISSUE TITLE
Disable partial formatter?

### ISSUE THREAD

**Issue by brandtdaniels** [MojtabaHs/iPhoneNumberField#23]
Is there a way to disable the partial formatter as seen in PhoneNumberKit?

`isPartialFormatterEnabled = false`

**Comment by MojtabaHs** [comment]
You can access all `PhoneNumberKit` properties from the `configuration` property (the last parameter of the initializer):

```
iPhoneNumberField(
    "Title",
    text: $text,
    isEditing: $isEditing,
    formatted: true) {
        $0.isPartialFormatterEnabled = false
}
```
