### ISSUE TITLE
Infinity loop after removing the number typed

### ISSUE THREAD

**Issue by elai950** [MojtabaHs/iPhoneNumberField#24]
I'm having an issue with the new release where I'm typing my number, and after removing what I typed before the FIRST number removed there is what looks like an infinity loop, the keyboard is flickering and the screen isn't responsive anymore.

I didn't encounter that on version 0.5.4 by the way.

**Comment by beskostyi-ad** [comment]
I have same issue too (0.5.4 works fine). But now I need `.autofillPrefix(true)`.

**Comment by Gbemiga** [comment]
@beskostyi-ad what do you do to resolve this issue? Did you just add `.autofillPrefix(true)` ? Also what version are you using?

**Comment by beskostyi-ad** [comment]
@Gbemiga I stoped use this lib in my project and coded needed logic by myself

**Comment by despie** [comment]
Inside `iPhoneNumberTextField.swift`, there is a warning `Modifying state during view update, this will cause undefined behavior.`, and this is exactly what's being reported to the debug console.
<img width="903" alt="Screenshot 2021-09-13 at 11 27 20" src="https://user-images.githubusercontent.com/20967939/133059611-81357ca4-6615-4eb8-96a1-54f9dd96d9ab.png">

The error reported is:
```
Modifying state during view update, this will cause undefined behavior.
on edit value: <PhoneNumberKit.PhoneNumberTextField: 0x7fc3d6883800; baseClass = UITextField; frame = (0 0; 350 31.5); text = ''; opaque = NO; gestureRecognizers = <NSArray: 0x600002d38210>; borderStyle = None; background = <_UITextFieldNoBackgroundProvider: 0x6000021c42e0: textfield=<PhoneNumberKit.PhoneNumberTextField 0x7fc3d6883800>>; layer = <CALayer: 0x600002368a80>>
```

**Comment by MojtabaHs** [comment]
This issue has not seen in v0.6.2.
Feel free to reopen and provide the reproducing sample code if you face it again
