### ISSUE TITLE
Is there a way to enable textContentType ?

### ISSUE THREAD

**Issue by smakus** [MojtabaHs/iPhoneNumberField#26]
It would be nice if iPhoneNumberField could work with the iOS autofill keyboard.  The only way to enable this is setting the textContentType, which appears to be disabled.  Is there a way to enable it?

**Comment by smakus** [comment]
I wound up forking the project and fixing this myself.  I'll create a pull request if anybody else needs this feature.  Otherwise you can check out my GitHub for the updated version, which also includes the placeholder text fix (kudos and thanks to other contributors).

**Comment by MichealSBingham** [comment]
Did you get this working? It doesn't seem to work on the master branch
