### ISSUE TITLE
Placeholder dont shows

### ISSUE THREAD

**Issue by krakatoor** [MojtabaHs/iPhoneNumberField#29]
<img width="1054" alt="Снимок экрана 2021-04-04 в 13 06 05" src="https://user-images.githubusercontent.com/38867359/113505330-ad240380-9546-11eb-987b-f4b99b416753.png">

**Comment by MojtabaHs** [comment]
<img width="1512" alt="Screen Shot 2022-08-08 at 2 05 25 PM" src="https://user-images.githubusercontent.com/15649873/183387698-205da8ee-6c87-48df-8637-d4c67c27a8e1.png">

No issues on v0.6.3
