### ISSUE TITLE
No Placeholder

### ISSUE THREAD

**Issue by JohnOHFS** [MojtabaHs/iPhoneNumberField#34]
I'm not able to see a placeholder text:

      iPhoneNumberField("Phone Number", text: $phoneNumber)
            .padding()
            .background(lightGreyColor)
            .cornerRadius(5.0)
            .padding(.bottom, 10)

**Comment by RayNastier** [comment]
same problem no placeholder in xcode 12.

**Comment by virusnik** [comment]
I have same problem

**Comment by djsurfeus** [comment]
Same issue. Not sure when it will be fixed

**Comment by munsifhayat** [comment]
Same issue not able to see placeholder text. 

Xcode 12

**Comment by JohnOHFS** [comment]
I just used a previous version to get it working.  Preference would be to use latest version.

**Comment by dj-bramdah** [comment]
@JohnOHFS which version ?

**Comment by JohnOHFS** [comment]
@dj-bramdah It works fine in 0.5.4

**Comment by ahmeturhan** [comment]
I have a same problem.
Version 0.6.1
XCode 12.4

**Comment by MichealSBingham** [comment]
Same problem. 
XCode 13.0

**Comment by Dreamystify** [comment]
there is a placeholder-fix branch

> @dj-bramdah It works fine in 0.5.4

Im using 0.5.4 and its not working for me

**Comment by jdhiro** [comment]
Also having this problem - Xcode 13

**Comment by mike-maws** [comment]
Still having this issue. What's worst is on the latest version, setting the text you set as binding to doesn't show up it's value at the start. Only when you start editing you see something, but the initial value is never shown.

**Comment by MojtabaHs** [comment]
Works on v0.6.3

<img width="1512" alt="Screen Shot 2022-08-08 at 2 05 25 PM" src="https://user-images.githubusercontent.com/15649873/183387698-205da8ee-6c87-48df-8637-d4c67c27a8e1.png">
