### ISSUE TITLE
How to get the country code?

### ISSUE THREAD

**Issue by tobyloki** [MojtabaHs/iPhoneNumberField#37]
I've started using the iPhoneNumberField and it works great for my need. However, I noticed that the text variable doesn't save the country code in it. How can I obtain the country code from iPhoneNumberField?

**Comment by maxcan** [comment]
If you set the country code to display:

```swift
    .prefixHidden(false)
    .autofillPrefix(true)
```

it will be included in the text binding "+1 415 555 1234"

**Comment by Nathan1258** [comment]
> If you set the country code to display:
> 
> ```swift
>     .prefixHidden(false)
>     .autofillPrefix(true)
> ```
> 
> it will be included in the text binding "+1 415 555 1234"

This does not seem to work no more...

**Comment by naticio** [comment]
this works for me, thanks!

```
flagHidden(false)
                            .flagSelectable(false)
                            .prefixHidden(false)
                            .autofillPrefix(true)
```

**Comment by MojtabaHs** [comment]
You only need to use `.prefixHidden(false)`. try not to handle the logic on the client side. if the user does not see the prefix, you may let your server detect the prefix! At least use the region instead.
