### ISSUE TITLE
It's not working on real device. 

### ISSUE THREAD

**Issue by ak29388** [MojtabaHs/iPhoneNumberField#38]
It's working fine with the simulator but it's not formatting the number on real device. I am testing on iPhone 12 pro. 

Here is my source code. 
[PhoneView.swift.zip](https://github.com/MojtabaHs/iPhoneNumberField/files/6907849/PhoneView.swift.zip)

 iPhoneNumberField("(000) 000-0000", text: $phoneNumber)
                    .maximumDigits(10)
                    .font(.custom(AvenirFont.medium.rawValue, size: 16))
                    .keyboardType(.phonePad)

It's formatting number in this way : 5765 656 585 but i need in this way : (5765) 656-585
![IMG_E5348C3643FA-1](https://user-images.githubusercontent.com/25545285/127661144-6fc5faad-f0ff-456d-9364-1d1daf8bb672.jpeg)

**Comment by MojtabaHs** [comment]
Seems like you have an issue with detecting the correct region for your desired formatting.

**Comment by MojtabaHs** [comment]
Closing the issue due to inactivity. Feel free to reopen if needed.
