### ISSUE TITLE
No proper way to get weather a phone number is valid or not

### ISSUE THREAD

**Issue by el-hoshino** [MojtabaHs/iPhoneNumberField#42]
I tried to read the code and couldn't find where I can get if an input number is valid or not. The `formatted` modifier can choose whether to format the text or not based on the validation of the input number, but it's only a visual difference, and the program itself can't determine that.

**Comment by el-hoshino** [comment]
Sorry, just found that we can pass `$0.isValidNumber` from `configuration` when making an `iPhoneNumberField`, so please let me mark it as closed.

For people who don't know how to achieve it, I'm pasting the working code below:

```swift
struct MyView: View {
    @State private var phoneNumber = ""
    @State private var isPhoneNumberValid = false

    var body: some View {
        iPhoneNumberField(text: $phoneNumber,
                          configuration: { isPhoneNumberValid = $0.isValidNumber })
    }
}
```

**Comment by r0otx** [comment]
> Sorry, just found that we can pass `$0.isValidNumber` from `configuration` when making an `iPhoneNumberField`, so please let me mark it as closed.
> 
> For people who don't know how to achieve it, I'm pasting the working code below:
> 
> ```swift
> struct MyView: View {
>     @State private var phoneNumber = ""
>     @State private var isPhoneNumberValid = false
> 
>     var body: some View {
>         iPhoneNumberField(text: $phoneNumber,
>                           configuration: { isPhoneNumberValid = $0.isValidNumber })
>     }
> }
> ```

If i'm use this case, I show warning: Modifying state during view update, this will cause undefined behavior.

**Comment by r0otx** [comment]
Sorry, I solved this problem, was need wrapped in async

```
                                DispatchQueue.main.async {
                                    isValid = value.isValidNumber
                                }
```
