### ISSUE TITLE
Auto Suggest does not work

### ISSUE THREAD

**Issue by austinchandra** [MojtabaHs/iPhoneNumberField#46]
Since the package currently voids the usage of .textContentType, it seems impossible to use auto suggest.

Works with autosuggest
```
        TextField("Phone Number", text: $myVar)
          .textContentType(.telephoneNumber)
          .keyboardType(.asciiCapableNumberPad)
```
Does not autosuggest
```
        iPhoneNumberField("Phone Number", text: $myVar)
          .maximumDigits(10)
          .textContentType(.telephoneNumber)
          .keyboardType(.asciiCapableNumberPad)
```

Would be great if you could add this functionality, or let me know if there are any workarounds

**Comment by austinchandra** [comment]
Looks like this was fixed in the source code, but never released into a new build. Is that right?

**Comment by MojtabaHs** [comment]
release from 0.6.3
