### ISSUE TITLE
KZ flag is not shown 

### ISSUE THREAD

**Issue by ZhannySunny** [MojtabaHs/iPhoneNumberField#47]
Hi! First of all, thank you for such a good library for phone flags! Unfortunately, when selecting Kazakhstan's flag it shows Russia flag instead. Could you please fix that?

**Comment by MojtabaHs** [comment]
sorry to hear that. Flags are generated from emojis and I have checked for these 3:
<img width="474" alt="Screen Shot 2022-08-08 at 4 14 31 PM" src="https://user-images.githubusercontent.com/15649873/183410817-44218dd0-04d2-4332-a284-0054e9daf140.png">

You can check out the code [here](https://github.com/marmelroy/PhoneNumberKit/blob/2e7fe71af50133cf07d14f5e2d3a760b68e56b44/PhoneNumberKit/UI/CountryCodePickerViewController.swift)

If there is a case that does not meet your needs fill an issue for this code feature/bug [here](https://github.com/marmelroy/PhoneNumberKit/issues/new)
