### ISSUE TITLE
Xcode complains with 'Modifying state during view update, this will cause undefined behavior.' when using iPhoneNumberField in SwiftUI project

### ISSUE THREAD

**Issue by jsanzmex** [MojtabaHs/iPhoneNumberField#48]
Hello!

Thanks for this awesome library.

I would like to know how the above Warning can be fixed.

XCode highlights the line `isFirstResponder.wrappedValue = true` inside these two functions:

```
public func textFieldDidBeginEditing(_ textField: UITextField) {
    isFirstResponder.wrappedValue = true
    onBeginEditing(textField as! PhoneNumberTextField)
}

public func textFieldDidEndEditing(_ textField: UITextField) {
    isFirstResponder.wrappedValue = false
    onEndEditing(textField as! PhoneNumberTextField)
}
```

As mentioned in the Title, my project is a SwiftUI project.

Any help you can provide will be highly appreciated.

Julio

**Comment by mylogon341** [comment]
Ive just seen this too. Were you able to resolve this or did you swap to a different library?

**Comment by Dave181295** [comment]
> `.clearButtonMode(.never)`
> this should fix your issue

Not working friend..

**Comment by MojtabaHs** [comment]
You should no longer see this warning on version `0.10.1`
