### ISSUE TITLE
Country code

### ISSUE THREAD

**Issue by YeJun-pixel** [MojtabaHs/iPhoneNumberField#49]
I want country code as I want phone verification system using firebase. How can I get country code?

**Comment by markjeschke** [comment]
Add the following to get the country code:
```
.prefixHidden(false)
.autofillPrefix(true)
```

**Comment by RayNastier** [comment]
@markjeschke but how to store the country code in a variable.

**Comment by MojtabaHs** [comment]
SwiftUI is a `UI` framework. You should not expect it to handle your logical codes.

You can get the country code of the desired region directly from the `PhoneNumberKit` with: `PhoneNumberKit().countryCode(for:)`

Also, you can get the region from the number with: `getRegionCode(of:)`
