### ISSUE TITLE
get phone code and country name

### ISSUE THREAD

**Issue by koolfreak** [MojtabaHs/iPhoneNumberField#54]
Hi, is there a way to get the phone code and country name for selected country? thanks

**Comment by MojtabaHs** [comment]
SwiftUI is a **UI** framework. You should not expect it to handle your logical codes.

You can get the country code of the desired region directly from the PhoneNumberKit with: `PhoneNumberKit().countryCode(for:)`

Also, you can get the region from the number with: `getRegionCode(of:)`

Don't forget to `import` it
