### ISSUE TITLE
Modifying state during view update, this will cause undefined behavior when I add .autofillPrefix(true)

### ISSUE THREAD

**Issue by X901** [MojtabaHs/iPhoneNumberField#55]
When I add` .autofillPrefix(true)` 
I got this error 

> Modifying state during view update, this will cause undefined behavior 
<img width="1384" alt="CleanShot 2022-07-29 at 21 48 39@2x" src="https://user-images.githubusercontent.com/16876982/181825416-1e81aa43-46a4-4b49-8e86-fc03f5d736a6.png">

**Comment by Dave181295** [comment]
Yup, same here 

![Screen Shot 2022-09-07 at 10 58 51](https://user-images.githubusercontent.com/76634618/188823279-a07a3159-cd85-48ca-8614-4d32feed12fa.png)

**Comment by cyberbarker** [comment]
Same behavior

**Comment by Archetapp** [comment]
Same behavior

**Comment by BrandonRCR** [comment]
Ever since iOS 16, I've had the same issue and my keyboard jumps up and down between each input

**Comment by Dave181295** [comment]
Any solutions friends?

**Comment by MojtabaHs** [comment]
> I still don't know why anyone will create library but didn't suppourt it !

I think you missed the `open-source` part of the `open-source library` my friend

**Comment by MojtabaHs** [comment]
You can use the direct change method to work around the issue:

```
            iPhoneNumberField(
                "Title",
                text: $text,
                isEditing: $isEditing,
                formatted: true
            ) {
                $0.withExamplePlaceholder = true // <- works as `autofillPrefix`
                $0.withPrefix = true // <- works as `!prefixHidden`
            }
```

Feel free to reopen this issue if it persists or mention this thread if you came with a PR ;)

**Comment by MojtabaHs** [comment]
Please provide the minimum complete setup code and your desired behavior. So that I can tell you wich settings you need to change directly. @X901

**Comment by MojtabaHs** [comment]
You should no longer see this warning on version `0.10.1`
