### ISSUE TITLE
Country code does not appear

### ISSUE THREAD

**Issue by raduncicen** [MojtabaHs/iPhoneNumberField#67]
<img width="765" alt="Screen Shot 2022-10-18 at 16 29 17" src="https://user-images.githubusercontent.com/44670959/196443527-ad3e9346-102b-47c4-a6e7-73352917e2e8.png">

Above is an example of how I implemented the iPhoneNumberField.
Though I configure the view to display country code it never does. Really rarely it displays it on certain countries, but in general it does not work. 
Also I cannot retrieve the full number "country code + entered number" with the binding.

Any suggestions?

I'm using 
Xcode 14.0.1
iPhone 14 simulator

**Comment by MojtabaHs** [comment]
You are overriding the placeholder by passing it in. So the placeholder does not append the country code.

You can get the number from the core `phoneNumber`:

```
iPhoneNumberField(
    text: $text
) { print($0.phoneNumber) }
```
It will return the phone number with all it's component only if the number is a valid phone number
