### ISSUE TITLE
iOS 16 Graph cycle errors

### ISSUE THREAD

**Issue by realszopen** [MojtabaHs/iPhoneNumberField#69]
Experiencing cycle errors in iOS 16.1, to be specific it is iPadOS 16.1, iPhoneNumberField worked marvellously before.

=== AttributeGraph: cycle detected through attribute 738376 ===

**Comment by cohen72** [comment]
@MojtabaHs 
I believe this can be resolved using the suggestion in https://stackoverflow.com/a/63142687/1014164, but 

wrapping `uiView.becomeFirstResponder()` with a `DispatchQueue.main.async`:

```
DispatchQueue.main.async {
     uiView.becomeFirstResponder()
}
```

https://github.com/MojtabaHs/iPhoneNumberField/blob/5298972c899ba3555a77549bebeace2e16bc927d/Sources/iPhoneNumberField/iPhoneNumberField.swift#L199

**Comment by vincentleclerc** [comment]
The problem is the repo's owner introduced a regression on release 0.10.1
After investigation, the easy fix is simply to target 0.10.0

Not sure what the initial "Undefined behaviour" issue was, but right now any view that has more than 1 textfield can't properly focused with 0.10.1 on iOS16+

Revert.

**Comment by Kn3cht** [comment]
Any updates on this issue?

**Comment by realszopen** [comment]
Well, not fixed, so in theory stale, but if not fixed and stale then I guess it means the whole project is kind of stale, does anyone have any updates on this issue?

**Comment by realszopen** [comment]
Issue remains in XCode 15 and iOS 17. Unable to update to current version of iPhoneNumberField sue to these graph cycle errors.

**Comment by tonybruess** [comment]
Still experiencing this
