### ISSUE TITLE
prefix field doesn't work as expected

### ISSUE THREAD

**Issue by samirsd** [MojtabaHs/iPhoneNumberField#70]
If flag is selected, the prefix field should be pre-populated and not editable. Clubhouse is a good reference for how this field should work.

**Comment by ooolzhas** [comment]
Yes, doesn't work for me either

**Comment by ChristianTrummer99** [comment]
same here.

**Comment by timelery** [comment]
Any update or known fix?

**Comment by goddamnyouryan** [comment]
the option `.autofillPrefix(true)` might fix your problems.
