### ISSUE TITLE
Please update PhoneNumberKit dependency to 3.5.5

### ISSUE THREAD

**Issue by cohen72** [MojtabaHs/iPhoneNumberField#77]
Please update PhoneNumberKit dependency to 3.5.5

**Comment by bojanstef** [comment]
Line 19 in [Package.swift](https://github.com/MojtabaHs/iPhoneNumberField/blob/5298972c899ba3555a77549bebeace2e16bc927d/Package.swift#LL19C70-L19C99) uses `.upToNextMajor(from: "3.4.5")` which pulls the latest PhoneNumberKit version of `3.5.8`
```swift
.package(url: "https://github.com/marmelroy/PhoneNumberKit", .upToNextMajor(from: "3.4.5"))
```
