### ISSUE TITLE
Keyboard infinity jumps

### ISSUE THREAD

**Issue by dimonuch1** [MojtabaHs/iPhoneNumberField#86]
We add iPhoneNumberField with  `.autofillPrefix(true)` and add `@Environment(\.presentationMode) var presentation` or `@Environment(\.dismiss) private var dismiss` in the same file. And in this case, is impossible to edit the text field.

**Comment by ColemanO** [comment]
I'm having the same issue and it seems to have to do with .autofillPrefix(true). If you don't add it, it doesn't happen.
