### ISSUE TITLE
Can add support for CocoaPods.

### ISSUE THREAD

**Issue by CosmicYogi** [MojtabaHs/iPhoneNumberField#89]
Hi,
Thank you for wring this great library.
Any specific reason it's not on CocoaPods?

**Comment by MojtabaHs** [comment]
> Hi,
> Thank you for wring this great library.
> Any specific reason it's not on CocoaPods?

Hello there,
No, just I'm not fan of using coca pods. :) 
If you believe this can be helpful, please feel free to open a PR and add support for it so I can merge it into the code.
