### ISSUE TITLE
Flag selectable does not work on tap, instead on long press

### ISSUE THREAD

**Issue by famictech2000** [MojtabaHs/iPhoneNumberField#9]
When I tap on the flag, nothing happens; instead if I long press the flag, then the sheet appears to select a country flag/country code.

**Comment by MojtabaHs** [comment]
I can't reproduce your issue. But I guess that you are using the field inside something intractable that delays the touch so you should hold your touch. Please upload a sample with your issue.

**Comment by MojtabaHs** [comment]
I'm going to close this since it is not reproducible. Feel free to reopen this when you upload your instructions or sample project.

**Comment by rawmean** [comment]
I'm using the field inside a `Form` (SwiftUI) and I have a similar problem. I don't think `Form` delays touch

**Comment by griebs23** [comment]
I had the same problem. A hideKeyboard onTapGesture was applied to containing Zstack. Moved it around and fixed.
