### ISSUE TITLE
Re-format phone number on country change

### ISSUE THREAD

**Issue by JohanAlbrectsen** [MojtabaHs/iPhoneNumberField#90]
iPhoneNumberField formats the phone number as it's typed, but when changing country, it doesn't re-format the previous phone number.

Otherwise, great library! Really well built,
Kind regards,
Johan.

**Comment by efremidze** [comment]
Still an issue

**Comment by JohanAlbrectsen** [comment]
Please re-open this issue and resolve, it's a large problem.
