### ISSUE TITLE
unable to import library

### ISSUE THREAD

**Issue by shahidghafoor00** [MojtabaHs/iPhoneNumberField#96]
<img width="677" alt="Screenshot 2024-01-25 at 1 22 26 AM" src="https://github.com/MojtabaHs/iPhoneNumberField/assets/10864149/2267fe5d-5d94-4127-acdc-84538eafe6f9">

**Comment by MojtabaHs** [comment]
Please share the log as text. The last line seems to have a clear description of this issue.
